<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>GastroHomeCA.Infrastructure.IntegrationTests</RootNamespace>
        <AssemblyName>GastroHomeCA.Infrastructure.IntegrationTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Xunit" />
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
